# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# The title of your site
title: Rubyconf Africa 2025

# The email address for site-related communication
email: organisers@rubyconf.africa

# A brief description of your site
description: >- # this means to ignore newlines until "baseurl:"
  <b>RubyConf Africa 2025</b> aims to connect together
                      Developers (Engineers), Designers and Entrepreneurs, from
                      across Africa to a <b>two day</b> conference from
                      <b>18th to 19th July, 2025 in Nairobi, Kenya</b> to have
                      conversations around the theme
                      <b>“Beyond code: Innovating for the future”</b>.

# The subpath of your site, e.g. /blog
baseurl: ""

# The base hostname & protocol for your site, e.g. http://example.com
url: "https://rubyconf.africa"

# Your GitLab username
gitlab_username: nairuby

# Your GitHub username
github_username: nairuby

# The current year
current_year: 2025

# Build settings
markdown: kramdown

# Plugins to use with Jekyll
plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-datapage-generator
#  - jekyll-assets

# Asset settings
#assets:
#  debug: false
#  compress:
#    css: true
#    js: true
#  js_compressor: uglifier
#  css_compressor: sass
#  sources:
#    - assets
#    - assets/js
#    - assets/css

# Minifier settngs
minifier:
  css:
    compress: true
    preserve_comments: false
  js:
    compress: true
    mangle: true
  html:
    remove_comments: true
    remove_empty_lines: true
    remove_blank_attributes: true
    remove_optional_tags: true
    collapse_whitespace: true
    conservative_collapse: true

page_gen:
  - data: "new_remote.speakers"
    template: "speaker"
    name: "name"
    dir: "speakers"
    extension: "html"
    index_files: false
    title: "name"
    slugify: true
    raw: false

# Collections of content
collections:
  speakers:
    output: true
    permalink: /speaker/:name/
  year-2015:
    output: true
    permalink: /2015/:path
  speakers_2015:
    output: true
    permalink: /2015/speaker/:name/
  year-2016:
    output: true
    permalink: /2016/:path
  speakers_2016:
    output: true
    permalink: /2016/speaker/:name/
  year-2017:
    output: true
    permalink: /2017/:path
  speakers_2017:
    output: true
    permalink: /2017/speaker/:name/
  year-2018:
    output: true
    permalink: /2018/:path
  speakers_2018:
    output: true
    permalink: /2018/speaker/:name/
  year-2019:
    output: true
    permalink: /2019/:path
  speakers_2019:
    output: true
    permalink: /2019/speaker/:name/
  year-2021:
    output: true
    permalink: /2021/:path
  speakers_2021:
    output: true
    permalink: /2021/speaker/:name/
  year-2024:
    output: true
    permalink: /2024/:path
  speakers_2024:
    output: true
    permalink: /2024/speaker/:name/
  year-2024-mini:
    output: true
    permalink: /2024-mini/:path
  speakers_2024_mini:
    output: true
    permalink: /2024-mini/speaker/:name/
  year-2025-mini:
    output: true
    permalink: /2024-mini/:path
  speakers_2025_mini:
    output: true
    permalink: /2024-mini/speaker/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - 2017speakers/
  - Makefile
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
