title: "Ruby Conf Africa 2024"
dates: "July 26-27, 2024"
venue: "KCA University"
location: "Nairobi, Kenya"
about: |
  ARC aims to unite entrepreneurs, developers, designers, and open-source
  contributors to tackle various challenges. By embracing entrepreneurship and
  open-source principles, ARC believes in offering comprehensive solutions to
  numerous issues. Attendees are equipped with both technological tools and
  entrepreneurial methodologies to maximize their potential and inspire others
  in their communities and beyond.
banners:
  - image: "../images/compressed/nairobi.jpg"
    alt: "Nairobi cityscape"
  - image: "../images/compressed/nairobi2.jpg"
    alt: "Nairobi cityscape 2"
