#!/usr/bin/env ruby
# frozen_string_literal: true

# Simple JavaScript bundler for modern assets
# Combines modern JS files while keeping them separate from legacy assets

require 'fileutils'

class ModernJsBundler
  MODERN_JS_DIR = 'assets/modern/js'
  OUTPUT_FILE = 'assets/modern/js/bundle.js'

  def self.build
    new.build
  end

  def build
    puts "🔨 Building modern JavaScript bundle..."
    
    begin
      # Read navigation.js first (it needs to be loaded before main.js)
      navigation_js = read_file('navigation.js')
      
      # Read main.js
      main_js = read_file('main.js')
      
      # Remove the import statement from main.js since we're bundling
      main_js_without_import = main_js.gsub(/import\s+['"]\.\/navigation\.js['"];?\s*/, '')
      
      # Combine files into bundle
      bundle_content = build_bundle_content(navigation_js, main_js_without_import)
      
      # Write bundle file
      File.write(OUTPUT_FILE, bundle_content)
      
      puts "✅ Modern JavaScript bundle created successfully at #{OUTPUT_FILE}"
    rescue => error
      puts "❌ Error building modern JavaScript: #{error.message}"
      exit 1
    end
  end

  private

  def read_file(filename)
    file_path = File.join(MODERN_JS_DIR, filename)
    
    unless File.exist?(file_path)
      raise "File not found: #{file_path}"
    end
    
    File.read(file_path)
  end

  def build_bundle_content(navigation_js, main_js)
    <<~JAVASCRIPT
      // Modern site JavaScript bundle - Generated automatically
      // Do not edit this file directly
      // Generated at: #{Time.now}

      #{navigation_js}

      #{main_js}
    JAVASCRIPT
  end
end

# Run the bundler if this script is executed directly
if __FILE__ == $0
  ModernJsBundler.build
end