name: Sync Google Sheet to Jekyll Data

on:
  workflow_dispatch:
#  push:
#    branches:
#      - Ft/Conf-details
#    paths:
#      - "_build/sync_google_sheets.rb"
#      - "_build/env_helper.rb"
#      - ".github/workflows/sync-google-sheets.yml"
#      - "Gemfile"
#      - "Gemfile.lock"
# schedule:
#  - cron: "0 6 * * *" # run daily at 6AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Install google-api-client system-wide
        run: gem install google-api-client -v 0.53.0

      - name: Verify Gem Installation
        run: |
          gem list google-apis-sheets_v4
          gem list googleauth

      - name: Run script to fetch Google Sheet data
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SHEET1_FILENAME: ${{ secrets.SHEET1_FILENAME }}
          SHEET1_NAME: ${{ secrets.SHEET1_NAME }}
          SHEET2_FILENAME: ${{ secrets.SHEET2_FILENAME }}
          SHEET2_NAME: ${{ secrets.SHEET2_NAME }}
          APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
        run: ruby _build/sync_google_sheets.rb

      - name: Verify output files
        run: |
          echo "File existence check:"
          ls _data/new_remote/*.yml 2>/dev/null || echo "No files found"
